### ISSUE TITLE
Verify not working

### ISSUE THREAD

**Issue by harishdrish123** [juhoen/hybrid-crypto-js#9]
Hello
crypt.varify is not working, getting below error:

/home/hyper1/Sawtooth-projects/auth/node_modules/node-forge/lib/util.js:1602
  input = input.replace(/[^A-Za-z0-9\+\/\=]/g, '');
                ^

TypeError: input.replace is not a function
    at Object.util.decode64 (/home/hyper1/Sawtooth-projects/auth/node_modules/node-forge/lib/util.js:1602:17)
    at Crypt.verify (/home/hyper1/Sawtooth-projects/auth/node_modules/hybrid-crypto-js/lib/crypt.js:48:32)
    at Object.<anonymous> (/home/hyper1/Sawtooth-projects/auth/server.js:36:19)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:240:19)

**Comment by nayanz89** [comment]
Got same issue. Please help
" undefined is not a function (evaluating 'input.replace(/[^A-Za-z0-9\+\/\=]/g, '')') "

**Comment by harishdrish123** [comment]
problem solved:
use this code to varify 
var varify = crypt.verify(senderPublicKe, decrypted.signature, decrypted.message)

**Comment by harishdrish123** [comment]
problem solved:
use this code to varify 
var varify = crypt.verify(senderPublicKe, decrypted.signature, decrypted.message)

**Comment by bwaters57** [comment]
Just ran into this same issue. Could @juhoen update the documentation to reflect this change to the verify method? That would eliminate the confusion here.

**Comment by cintolas** [comment]
should it throw an error or should it just return false?

**Comment by cintolas** [comment]
The error is in the documentation

https://github.com/juhoen/hybrid-crypto-js/pull/13/commits/a808761e3789b71ad9b066fc5836052bd70a64b0

**Comment by juhoen** [comment]
Thank you for your support.
